SELECT * FROM BRIGHT_TV.VIEWERSHIP.V_CLEAN_VIEWING_SESSIONS LIMIT 10

CREATE OR REPLACE VIEW BRIGHT_TV.VIEWERSHIP.V_CLEAN_VIEWING_SESSIONS AS
SELECT
    USERID          AS USER_ID,
    CHANNEL2        AS CHANNEL,
    RECORDDATE2     AS RECORD_DATE,          -- already parsed as TIMESTAMP_NTZ
    DURATION2       AS DURATION             -- already TIME
FROM BRIGHT_TV.VIEWERSHIP.VIEWS;

SELECT * FROM BRIGHT_TV.VIEWERSHIP.V_CLEAN_VIEWING_SESSIONS LIMIT 10;

SELECT 
    DURATION2,
    TIMEADD(HOUR, 1, DURATION2) AS ONE_HOUR_LATER
FROM BRIGHT_TV.VIEWERSHIP.VIEWS
LIMIT 5;
--SELECT* FROM BRIGHT_TV.VIEWERSHIP.USERPROFILE LIMIT 10





SELECT
   -- DATE(s.RECORDDATE2) AS VIEW_DATE,
    --DAYNAME(s.RECORDDATE2) AS DAY_OF_WEEK,
    --HOUR(s.RECORDDATE2) + 2 AS HOUR_SAST,   

    p.PROVINCE,
    CASE 
        WHEN p.AGE < 25 THEN '18-24'
        WHEN p.AGE BETWEEN 25 AND 34 THEN '25-34'
        WHEN p.AGE BETWEEN 35 AND 44 THEN '35-44'
        WHEN p.AGE BETWEEN 45 AND 54 THEN '45-54'
        ELSE '55+' 
    END AS AGE_GROUP,
    p.GENDER,
    p.RACE,

    COUNT(*) AS TOTAL_SESSIONS,
    COUNT(DISTINCT s.USERID) AS UNIQUE_USERS,

    -- No duration calculation — just count sessions
    -- (You can still use AVG(DURATION2) if needed, but it won't be numeric)

    RANK() OVER (ORDER BY COUNT(*) ASC) AS CONSUMPTION_RANK

FROM BRIGHT_TV.VIEWERSHIP.VIEWS s
LEFT JOIN BRIGHT_TV.VIEWERSHIP.USERPROFILE p
    ON s.USERID = p.USERID

GROUP BY 
  -- DATE(s.RECORDDATE2),
   -- DAYNAME(s.RECORDDATE2),
   -- HOUR(s.RECORDDATE2) + 2,
    p.PROVINCE,
    CASE 
        WHEN p.AGE < 25 THEN '18-24'
        WHEN p.AGE BETWEEN 25 AND 34 THEN '25-34'
        WHEN p.AGE BETWEEN 35 AND 44 THEN '35-44'
        WHEN p.AGE BETWEEN 45 AND 54 THEN '45-54'
        ELSE '55+' 
    END,
    p.GENDER,
    p.RACE

ORDER BY 
    CONSUMPTION_RANK,          -- lowest consumption first
    --VIEW_DATE DESC,
    TOTAL_SESSIONS DESC

LIMIT 1000;
